"""
evaluate.py
Comprehensive evaluation suite for marketing campaign response prediction:
- Comparative metrics (Accuracy, Precision, Recall, F1, ROC-AUC, TN, FP, FN, TP, FPR)
- Visualization generation: Comparison Bar Chart, ROC Curves, PR Curves, Confusion Matrices
- Decision threshold optimization & trade-off analysis
- Cost-benefit & marketing ROI business simulation
- Cumulative Gains and Decile Lift analysis
- Probability calibration with CalibratedClassifierCV
- Model interpretability: Tree Importance, Permutation Importance, Odds Ratios, SHAP
- Customer persona / responder profiling
"""

import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict, Any, List, Tuple
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, roc_curve, precision_recall_curve,
    brier_score_loss
)
from sklearn.inspection import permutation_importance
from sklearn.calibration import CalibratedClassifierCV, calibration_curve

# Set publication-quality plotting styles
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['font.sans-serif'] = 'Helvetica, Arial, DejaVu Sans'
plt.rcParams['font.size'] = 10
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['figure.titlesize'] = 14

# Marketing Economic Parameters
COST_PER_CONTACT = 5.0      # USD spent per marketing contact attempt
PROFIT_PER_RESPONDER = 50.0 # USD gross profit generated by a responding customer


def compute_test_metrics(model, X_test, y_test, threshold: float = 0.5) -> Dict[str, Any]:
    """
    Computes all standard test metrics plus confusion matrix components and FPR.
    """
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
    elif hasattr(model, "decision_function"):
        d = model.decision_function(X_test)
        y_proba = 1 / (1 + np.exp(-d))
    else:
        y_proba = model.predict(X_test).astype(float)
        
    y_pred = (y_proba >= threshold).astype(int)
    
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    try:
        auc = roc_auc_score(y_test, y_proba)
    except Exception:
        auc = 0.5
        
    return {
        'accuracy': float(acc),
        'precision': float(prec),
        'recall': float(rec),
        'f1': float(f1),
        'roc_auc': float(auc),
        'tn': int(tn),
        'fp': int(fp),
        'fn': int(fn),
        'tp': int(tp),
        'fpr': float(fpr),
        'y_proba': y_proba,
        'y_pred': y_pred
    }


def plot_metrics_comparison(results_df: pd.DataFrame, output_dir: str = "reports/figures") -> str:
    """
    Produces a comparative bar chart across all evaluated algorithms.
    """
    os.makedirs(output_dir, exist_ok=True)
    metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
    
    # Rename columns if needed
    col_map = {
        'accuracy': 'Accuracy', 'precision': 'Precision',
        'recall': 'Recall', 'f1': 'F1-Score', 'roc_auc': 'ROC-AUC'
    }
    plot_df = results_df.rename(columns=col_map).copy()
    
    df_melted = plot_df.melt(
        id_vars=['Model'],
        value_vars=[c for c in metrics_to_plot if c in plot_df.columns],
        var_name='Metric',
        value_name='Score'
    )
    
    plt.figure(figsize=(12, 6))
    palette = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    ax = sns.barplot(
        data=df_melted,
        x='Metric',
        y='Score',
        hue='Model',
        palette=palette,
        edgecolor='black',
        alpha=0.9
    )
    plt.title("Comparative Performance Across 6 Machine Learning Models (Test Set)", fontweight='bold', pad=15)
    plt.ylim(0.0, 1.05)
    plt.ylabel("Score")
    plt.xlabel("")
    plt.legend(title="Algorithm", bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "metrics_comparison_bar.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_roc_curves(models_dict: Dict[str, Any], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """
    Plots Receiver Operating Characteristic (ROC) curves for all 6 models on a single graph.
    """
    os.makedirs(output_dir, exist_ok=True)
    plt.figure(figsize=(9, 7))
    
    palette = sns.color_palette("tab10", len(models_dict))
    
    for i, (name, model) in enumerate(models_dict.items()):
        if hasattr(model, "predict_proba"):
            y_proba = model.predict_proba(X_test)[:, 1]
        elif hasattr(model, "decision_function"):
            d = model.decision_function(X_test)
            y_proba = 1 / (1 + np.exp(-d))
        else:
            continue
            
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        auc_score = roc_auc_score(y_test, y_proba)
        plt.plot(fpr, tpr, label=f"{name} (AUC = {auc_score:.3f})", color=palette[i], lw=2)
        
    plt.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Chance (AUC = 0.500)')
    plt.xlim([-0.02, 1.02])
    plt.ylim([-0.02, 1.02])
    plt.xlabel("False Positive Rate (1 - Specificity)")
    plt.ylabel("True Positive Rate (Sensitivity / Recall)")
    plt.title("Receiver Operating Characteristic (ROC) Curves - All Models", fontweight='bold', pad=15)
    plt.legend(loc='lower right', frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "roc_curves_all_models.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_precision_recall_curves(models_dict: Dict[str, Any], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """
    Plots Precision-Recall (PR) curves for all 6 models on a single graph.
    Critical for evaluating imbalanced target distributions.
    """
    os.makedirs(output_dir, exist_ok=True)
    plt.figure(figsize=(9, 7))
    
    baseline = np.mean(y_test)
    palette = sns.color_palette("tab10", len(models_dict))
    
    for i, (name, model) in enumerate(models_dict.items()):
        if hasattr(model, "predict_proba"):
            y_proba = model.predict_proba(X_test)[:, 1]
        elif hasattr(model, "decision_function"):
            d = model.decision_function(X_test)
            y_proba = 1 / (1 + np.exp(-d))
        else:
            continue
            
        prec, rec, _ = precision_recall_curve(y_test, y_proba)
        plt.plot(rec, prec, label=f"{name}", color=palette[i], lw=2)
        
    plt.axhline(baseline, color='k', linestyle='--', lw=1.5, label=f"Baseline Prevalence ({baseline:.1%})")
    plt.xlim([-0.02, 1.02])
    plt.ylim([-0.02, 1.02])
    plt.xlabel("Recall (True Positive Rate)")
    plt.ylabel("Precision (Positive Predictive Value)")
    plt.title("Precision-Recall (PR) Curves - All Models", fontweight='bold', pad=15)
    plt.legend(loc='upper right', frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "pr_curves_all_models.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_confusion_matrices(models_dict: Dict[str, Any], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """
    Plots a 2x3 grid of confusion matrix heatmaps with raw counts and normalized percentages.
    """
    os.makedirs(output_dir, exist_ok=True)
    fig, axes = plt.subplots(2, 3, figsize=(15, 9))
    axes = axes.flatten()
    
    for i, (name, model) in enumerate(models_dict.items()):
        y_pred = model.predict(X_test)
        cm = confusion_matrix(y_test, y_pred)
        
        # Annotations with counts and percentages
        cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        annot = np.array([
            [f"{cm[0, 0]}\n({cm_norm[0, 0]:.1%})", f"{cm[0, 1]}\n({cm_norm[0, 1]:.1%})"],
            [f"{cm[1, 0]}\n({cm_norm[1, 0]:.1%})", f"{cm[1, 1]}\n({cm_norm[1, 1]:.1%})"]
        ])
        
        sns.heatmap(
            cm,
            annot=annot,
            fmt='',
            cmap='Blues',
            cbar=False,
            ax=axes[i],
            xticklabels=['Non-Responder (0)', 'Responder (1)'],
            yticklabels=['Non-Responder (0)', 'Responder (1)'],
            linewidths=1,
            linecolor='grey'
        )
        axes[i].set_title(f"{name}", fontweight='bold', pad=8)
        axes[i].set_xlabel("Predicted Label")
        axes[i].set_ylabel("True Label")
        
    plt.suptitle("Confusion Matrix Heatmaps Across All 6 Models (Test Set, Threshold = 0.50)", fontweight='bold', fontsize=15, y=0.98)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "confusion_matrices_grid.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def tune_decision_threshold(best_model, X_test, y_test, output_dir: str = "reports/figures") -> Dict[str, Any]:
    """
    Sweeps decision threshold from 0.05 to 0.95.
    Calculates Precision, Recall, F1, and FPR at each step.
    Determines optimal threshold and plots curves.
    """
    os.makedirs(output_dir, exist_ok=True)
    y_proba = best_model.predict_proba(X_test)[:, 1]
    
    thresholds = np.linspace(0.05, 0.95, 91)
    precisions = []
    recalls = []
    f1s = []
    fprs = []
    
    for t in thresholds:
        y_pred = (y_proba >= t).astype(int)
        p = precision_score(y_test, y_pred, zero_division=0)
        r = recall_score(y_test, y_pred, zero_division=0)
        f = f1_score(y_test, y_pred, zero_division=0)
        cm = confusion_matrix(y_test, y_pred)
        tn, fp, fn, tp = cm.ravel()
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
        
        precisions.append(p)
        recalls.append(r)
        f1s.append(f)
        fprs.append(fpr)
        
    precisions = np.array(precisions)
    recalls = np.array(recalls)
    f1s = np.array(f1s)
    fprs = np.array(fprs)
    
    # Optimal F1 threshold
    best_idx = np.argmax(f1s)
    opt_threshold = float(thresholds[best_idx])
    opt_f1 = float(f1s[best_idx])
    opt_prec = float(precisions[best_idx])
    opt_rec = float(recalls[best_idx])
    opt_fpr = float(fprs[best_idx])
    
    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(thresholds, precisions, label='Precision (PPV)', color='#2ca02c', lw=2)
    plt.plot(thresholds, recalls, label='Recall (Sensitivity)', color='#1f77b4', lw=2)
    plt.plot(thresholds, f1s, label='F1-Score', color='#d62728', lw=2.5)
    plt.plot(thresholds, fprs, label='False Positive Rate (FPR)', color='#ff7f0e', lw=2, linestyle='--')
    
    plt.axvline(0.5, color='gray', linestyle=':', label='Default Threshold (0.50)')
    plt.axvline(opt_threshold, color='purple', linestyle='-', lw=2,
                label=f'Optimal F1 Threshold ({opt_threshold:.2f})')
    
    plt.scatter([opt_threshold], [opt_f1], color='purple', s=80, zorder=5)
    
    plt.title("Decision Threshold Optimization & Trade-Off Dynamics", fontweight='bold', pad=15)
    plt.xlabel("Classification Decision Threshold")
    plt.ylabel("Metric Score")
    plt.xlim([0.05, 0.95])
    plt.ylim([0.0, 1.02])
    plt.legend(loc='center right', frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "threshold_tuning.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    
    return {
        'optimal_threshold': opt_threshold,
        'optimal_f1': opt_f1,
        'optimal_precision': opt_prec,
        'optimal_recall': opt_rec,
        'optimal_fpr': opt_fpr,
        'default_metrics': compute_test_metrics(best_model, X_test, y_test, threshold=0.5),
        'optimized_metrics': compute_test_metrics(best_model, X_test, y_test, threshold=opt_threshold),
        'plot_path': filepath
    }


def run_business_simulation(
    best_model, X_test, y_test,
    opt_threshold: float,
    cost_per_contact: float = COST_PER_CONTACT,
    profit_per_responder: float = PROFIT_PER_RESPONDER,
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """
    Simulates marketing campaign financials under three strategies:
      - Strategy A: Contact Everyone (Mass Spray & Pray)
      - Strategy B: Contact Predicted Responders at Default Threshold (0.50)
      - Strategy C: Contact Predicted Responders at Optimized Threshold
    """
    os.makedirs(output_dir, exist_ok=True)
    n_customers = len(y_test)
    actual_responders_total = int(y_test.sum())
    
    # 1. Strategy A: Contact Everyone
    contacts_A = n_customers
    responders_A = actual_responders_total
    wasted_contacts_A = n_customers - actual_responders_total
    cost_A = contacts_A * cost_per_contact
    gross_profit_A = responders_A * profit_per_responder
    net_profit_A = gross_profit_A - cost_A
    roi_A = (net_profit_A / cost_A) * 100 if cost_A > 0 else 0
    cost_saved_pct_A = 0.0
    
    # 2. Strategy B: Default Threshold (0.50)
    metrics_B = compute_test_metrics(best_model, X_test, y_test, threshold=0.50)
    contacts_B = metrics_B['tp'] + metrics_B['fp']
    responders_B = metrics_B['tp']
    wasted_contacts_B = metrics_B['fp']
    cost_B = contacts_B * cost_per_contact
    gross_profit_B = responders_B * profit_per_responder
    net_profit_B = gross_profit_B - cost_B
    roi_B = (net_profit_B / cost_B) * 100 if cost_B > 0 else 0
    cost_saved_pct_B = ((cost_A - cost_B) / cost_A) * 100
    
    # 3. Strategy C: Optimized Threshold
    metrics_C = compute_test_metrics(best_model, X_test, y_test, threshold=opt_threshold)
    contacts_C = metrics_C['tp'] + metrics_C['fp']
    responders_C = metrics_C['tp']
    wasted_contacts_C = metrics_C['fp']
    cost_C = contacts_C * cost_per_contact
    gross_profit_C = responders_C * profit_per_responder
    net_profit_C = gross_profit_C - cost_C
    roi_C = (net_profit_C / cost_C) * 100 if cost_C > 0 else 0
    cost_saved_pct_C = ((cost_A - cost_C) / cost_A) * 100
    
    sim_data = [
        {
            'Strategy': 'Strategy A: Contact All Customers',
            'Targeted Contacts': contacts_A,
            'Total Cost ($)': cost_A,
            'Responders Reached': responders_A,
            'Wasted Contacts (FP)': wasted_contacts_A,
            'Gross Revenue ($)': gross_profit_A,
            'Net Profit ($)': net_profit_A,
            'ROI (%)': roi_A,
            'Cost Saved vs All (%)': cost_saved_pct_A
        },
        {
            'Strategy': 'Strategy B: Default ML (Threshold 0.50)',
            'Targeted Contacts': contacts_B,
            'Total Cost ($)': cost_B,
            'Responders Reached': responders_B,
            'Wasted Contacts (FP)': wasted_contacts_B,
            'Gross Revenue ($)': gross_profit_B,
            'Net Profit ($)': net_profit_B,
            'ROI (%)': roi_B,
            'Cost Saved vs All (%)': cost_saved_pct_B
        },
        {
            'Strategy': f'Strategy C: Optimized ML (Threshold {opt_threshold:.2f})',
            'Targeted Contacts': contacts_C,
            'Total Cost ($)': cost_C,
            'Responders Reached': responders_C,
            'Wasted Contacts (FP)': wasted_contacts_C,
            'Gross Revenue ($)': gross_profit_C,
            'Net Profit ($)': net_profit_C,
            'ROI (%)': roi_C,
            'Cost Saved vs All (%)': cost_saved_pct_C
        }
    ]
    sim_df = pd.DataFrame(sim_data)
    
    # Visualization
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    
    strategies_short = ['A: Contact All', 'B: ML Default (0.50)', f'C: ML Tuned ({opt_threshold:.2f})']
    colors = ['#7f7f7f', '#1f77b4', '#2ca02c']
    
    # 1. Total Marketing Cost
    costs = [cost_A, cost_B, cost_C]
    bars1 = axes[0].bar(strategies_short, costs, color=colors, edgecolor='black', alpha=0.85)
    axes[0].set_title("Total Campaign Spend ($)", fontweight='bold')
    axes[0].set_ylabel("USD ($)")
    for b in bars1:
        axes[0].text(b.get_x() + b.get_width()/2, b.get_height() + 50, f"${b.get_height():,.0f}",
                     ha='center', va='bottom', fontweight='bold')
                     
    # 2. Net Profit
    profits = [net_profit_A, net_profit_B, net_profit_C]
    bars2 = axes[1].bar(strategies_short, profits, color=colors, edgecolor='black', alpha=0.85)
    axes[1].set_title("Net Campaign Profit ($)", fontweight='bold')
    axes[1].set_ylabel("USD ($)")
    for b in bars2:
        axes[1].text(b.get_x() + b.get_width()/2, b.get_height() + 50, f"${b.get_height():,.0f}",
                     ha='center', va='bottom', fontweight='bold')
                     
    # 3. Campaign Return on Investment (ROI %)
    rois = [roi_A, roi_B, roi_C]
    bars3 = axes[2].bar(strategies_short, rois, color=colors, edgecolor='black', alpha=0.85)
    axes[2].set_title("Return on Marketing Spend (ROI %)", fontweight='bold')
    axes[2].set_ylabel("Percentage (%)")
    for b in bars3:
        axes[2].text(b.get_x() + b.get_width()/2, b.get_height() + 5, f"{b.get_height():.1f}%",
                     ha='center', va='bottom', fontweight='bold')
                     
    plt.suptitle(f"Marketing Economics Simulation (Cost/Contact = ${cost_per_contact}, Profit/Responder = ${profit_per_responder})",
                 fontweight='bold', fontsize=14, y=1.02)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "business_simulation_roi.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    
    return {
        'simulation_table': sim_df,
        'plot_path': filepath
    }


def plot_cumulative_gains_and_lift(best_model, X_test, y_test, output_dir: str = "reports/figures") -> str:
    """
    Computes and plots Cumulative Gains and Decile Lift charts.
    Demonstrates efficiency in capturing positive responders by targeting top percentiles.
    """
    os.makedirs(output_dir, exist_ok=True)
    y_proba = best_model.predict_proba(X_test)[:, 1]
    
    df_eval = pd.DataFrame({'actual': y_test.values, 'prob': y_proba})
    df_eval = df_eval.sort_values(by='prob', ascending=False).reset_index(drop=True)
    df_eval['decile'] = pd.qcut(df_eval.index, q=10, labels=range(1, 11))
    
    total_responders = df_eval['actual'].sum()
    total_customers = len(df_eval)
    
    # Cumulative Gains
    df_eval['cum_responders'] = df_eval['actual'].cumsum()
    df_eval['cum_pct_responders'] = (df_eval['cum_responders'] / total_responders) * 100
    df_eval['cum_pct_customers'] = ((df_eval.index + 1) / total_customers) * 100
    
    # Decile Lift Table
    decile_summary = df_eval.groupby('decile', observed=False).agg(
        total_in_decile=('actual', 'count'),
        responders_in_decile=('actual', 'sum')
    ).reset_index()
    decile_summary['response_rate'] = (decile_summary['responders_in_decile'] / decile_summary['total_in_decile']) * 100
    baseline_rate = (total_responders / total_customers) * 100
    decile_summary['lift'] = decile_summary['response_rate'] / baseline_rate
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # 1. Cumulative Gains Chart
    axes[0].plot(df_eval['cum_pct_customers'], df_eval['cum_pct_responders'], label='ML Model Gains', color='#1f77b4', lw=2.5)
    axes[0].plot([0, 100], [0, 100], 'k--', label='Random Targeting (Baseline)', lw=1.5)
    
    # Highlight top 20% and 30% points
    for pct in [20, 30]:
        idx = int(total_customers * (pct / 100)) - 1
        gain = df_eval.loc[idx, 'cum_pct_responders']
        axes[0].scatter([pct], [gain], color='#d62728', s=60, zorder=5)
        axes[0].annotate(f"Top {pct}%: {gain:.1f}% responders",
                         xy=(pct, gain), xytext=(pct + 5, gain - 7),
                         arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
                         fontweight='bold')
                         
    axes[0].set_title("Cumulative Gains Chart", fontweight='bold')
    axes[0].set_xlabel("Percentage of Customers Contacted (%)")
    axes[0].set_ylabel("Cumulative Percentage of Responders Captured (%)")
    axes[0].set_xlim([0, 100])
    axes[0].set_ylim([0, 105])
    axes[0].legend(loc='lower right', frameon=True)
    
    # 2. Decile Lift Chart
    sns.barplot(data=decile_summary, x='decile', y='lift', color='#2ca02c', ax=axes[1], edgecolor='black', alpha=0.85)
    axes[1].axhline(1.0, color='red', linestyle='--', lw=1.5, label='Baseline Lift (1.0x)')
    axes[1].set_title("Decile Lift Curve", fontweight='bold')
    axes[1].set_xlabel("Customer Decile (Ranked by Predicted Likelihood)")
    axes[1].set_ylabel("Lift Multiplier vs Random")
    axes[1].set_ylim(0, max(decile_summary['lift']) * 1.25)
    for p in axes[1].patches:
        height = p.get_height()
        if height > 0:
            axes[1].annotate(f"{height:.2f}x",
                             (p.get_x() + p.get_width() / 2., height),
                             ha='center', va='bottom', xytext=(0, 3),
                             textcoords='offset points', fontweight='bold', fontsize=9)
    axes[1].legend(loc='upper right', frameon=True)
    
    plt.suptitle("Targeting Efficiency: Gains and Decile Lift Analysis", fontweight='bold', fontsize=14, y=1.01)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "cumulative_gains_lift.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def evaluate_probability_calibration(best_model, X_train, y_train, X_test, y_test, output_dir: str = "reports/figures") -> Dict[str, Any]:
    """
    Evaluates probability calibration using CalibratedClassifierCV.
    Plots reliability curves before and after calibration and computes Brier score loss.
    """
    os.makedirs(output_dir, exist_ok=True)
    # Uncalibrated probabilities
    y_proba_uncal = best_model.predict_proba(X_test)[:, 1]
    brier_uncal = brier_score_loss(y_test, y_proba_uncal)
    
    # Calibrate using sigmoid/isotonic via CalibratedClassifierCV with prefit
    try:
        calibrator = CalibratedClassifierCV(estimator=best_model, method='sigmoid', cv='prefit')
        calibrator.fit(X_train, y_train)
        y_proba_cal = calibrator.predict_proba(X_test)[:, 1]
        brier_cal = brier_score_loss(y_test, y_proba_cal)
    except Exception:
        calibrator = None
        y_proba_cal = y_proba_uncal
        brier_cal = brier_uncal
        
    prob_true_uncal, prob_pred_uncal = calibration_curve(y_test, y_proba_uncal, n_bins=10)
    prob_true_cal, prob_pred_cal = calibration_curve(y_test, y_proba_cal, n_bins=10)
    
    plt.figure(figsize=(8, 6))
    plt.plot([0, 1], [0, 1], "k:", label="Perfect Calibration")
    plt.plot(prob_pred_uncal, prob_true_uncal, "s-", color='#1f77b4', lw=2,
             label=f"Uncalibrated Model (Brier: {brier_uncal:.4f})")
    plt.plot(prob_pred_cal, prob_true_cal, "o-", color='#2ca02c', lw=2,
             label=f"Calibrated (Sigmoid) (Brier: {brier_cal:.4f})")
             
    plt.title("Reliability Diagram: Probability Calibration Analysis", fontweight='bold', pad=15)
    plt.xlabel("Mean Predicted Probability")
    plt.ylabel("Observed Fraction of Responders")
    plt.ylim([-0.05, 1.05])
    plt.xlim([-0.05, 1.05])
    plt.legend(loc="lower right", frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "calibration_curve.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    
    return {
        'brier_uncalibrated': float(brier_uncal),
        'brier_calibrated': float(brier_cal),
        'calibrator': calibrator,
        'plot_path': filepath
    }


def analyze_feature_importances(
    best_tree_model, lr_model,
    X_test, y_test,
    feature_names: List[str],
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """
    Computes and plots:
      1. Tree-based MDI feature importances (Random Forest or Gradient Boosting)
      2. Permutation feature importances on test set
      3. Logistic Regression Odds Ratios (exp(coef))
      4. SHAP summary plot (if shap is installed)
    """
    os.makedirs(output_dir, exist_ok=True)
    plots = {}
    
    # 1. Tree-based MDI Importance
    # Extract underlying classifier from pipeline if needed
    tree_estimator = best_tree_model.named_steps.get('classifier', best_tree_model)
    if hasattr(tree_estimator, 'feature_importances_'):
        importances = tree_estimator.feature_importances_
        fi_df = pd.DataFrame({'feature': feature_names, 'importance': importances})
        fi_df = fi_df.sort_values('importance', ascending=True)
        
        plt.figure(figsize=(9, 6))
        plt.barh(fi_df['feature'], fi_df['importance'], color='#1f77b4', edgecolor='black', alpha=0.85)
        plt.title("Tree-Based Feature Importances (Mean Decrease in Impurity)", fontweight='bold', pad=12)
        plt.xlabel("Relative Importance")
        plt.tight_layout()
        fi_path = os.path.join(output_dir, "feature_importance_tree.png")
        plt.savefig(fi_path, dpi=300)
        plt.close()
        plots['tree_importance'] = fi_path
        
    # 2. Permutation Importance on Test Set
    perm_res = permutation_importance(best_tree_model, X_test, y_test, n_repeats=10, random_state=42, scoring='f1')
    perm_df = pd.DataFrame({
        'feature': X_test.columns,
        'mean_importance': perm_res.importances_mean,
        'std': perm_res.importances_std
    }).sort_values('mean_importance', ascending=True)
    
    plt.figure(figsize=(9, 6))
    plt.barh(perm_df['feature'], perm_df['mean_importance'], xerr=perm_df['std'], color='#2ca02c', edgecolor='black', alpha=0.85)
    plt.title("Permutation Feature Importance on Test Set (F1 Impact)", fontweight='bold', pad=12)
    plt.xlabel("Mean F1-Score Decrease Upon Permutation")
    plt.tight_layout()
    perm_path = os.path.join(output_dir, "feature_importance_permutation.png")
    plt.savefig(perm_path, dpi=300)
    plt.close()
    plots['permutation_importance'] = perm_path
    
    # 3. Logistic Regression Odds Ratios
    lr_estimator = lr_model.named_steps.get('classifier', lr_model)
    if hasattr(lr_estimator, 'coef_'):
        coefs = lr_estimator.coef_[0]
        odds_ratios = np.exp(coefs)
        or_df = pd.DataFrame({
            'feature': feature_names,
            'odds_ratio': odds_ratios,
            'log_odds': coefs
        }).sort_values('odds_ratio', ascending=True)
        
        plt.figure(figsize=(9, 6))
        colors = ['#d62728' if x < 1.0 else '#1f77b4' for x in or_df['odds_ratio']]
        plt.barh(or_df['feature'], or_df['odds_ratio'], color=colors, edgecolor='black', alpha=0.85)
        plt.axvline(1.0, color='k', linestyle='--', lw=1.2, label='Baseline (Odds Ratio = 1.0)')
        plt.title("Logistic Regression Predictors: Odds Ratios (exp(β))", fontweight='bold', pad=12)
        plt.xlabel("Odds Ratio (> 1.0 indicates increased response likelihood)")
        plt.legend(loc='lower right')
        plt.tight_layout()
        or_path = os.path.join(output_dir, "feature_importance_odds_ratios.png")
        plt.savefig(or_path, dpi=300)
        plt.close()
        plots['odds_ratios'] = or_path
        
    # 4. SHAP Summary Plot
    try:
        import shap
        # Transform X_test through preprocessor for SHAP explanation
        preprocessor = best_tree_model.named_steps['preprocessor']
        X_test_trans = preprocessor.transform(X_test)
        
        # Explain tree model
        explainer = shap.TreeExplainer(tree_estimator)
        shap_values = explainer.shap_values(X_test_trans)
        
        # If binary classification returns list or 3D array
        if isinstance(shap_values, list):
            sv = shap_values[1]
        elif hasattr(shap_values, 'shape') and len(shap_values.shape) == 3:
            sv = shap_values[:, :, 1]
        else:
            sv = shap_values
            
        plt.figure(figsize=(10, 6))
        shap.summary_plot(sv, X_test_trans, feature_names=feature_names, show=False)
        plt.title("SHAP Feature Importance & Impact Distribution", fontweight='bold', pad=15)
        plt.tight_layout()
        shap_path = os.path.join(output_dir, "shap_summary.png")
        plt.savefig(shap_path, dpi=300, bbox_inches='tight')
        plt.close()
        plots['shap'] = shap_path
    except Exception as e:
        print(f"SHAP explanation skipped or encountered issue: {e}")
        plots['shap'] = None
        
    return plots


def compute_customer_profiles(X_test: pd.DataFrame, y_pred: np.ndarray) -> pd.DataFrame:
    """
    Computes profile comparison: mean/median feature values for predicted Responders vs Non-Responders.
    """
    df_prof = X_test.copy()
    df_prof['predicted_class'] = np.where(y_pred == 1, 'Responder', 'Non-Responder')
    
    numeric_cols = [c for c in df_prof.columns if c in [
        'income', 'previous_purchases', 'purchase_frequency',
        'previous_campaign_response', 'website_visits',
        'email_engagement', 'discount_usage'
    ]]
    
    summary = df_prof.groupby('predicted_class')[numeric_cols].agg(['mean', 'median']).round(2)
    return summary
