"""
evaluate.py
Comprehensive evaluation suite for marketing campaign response prediction:
- Comparative metrics (Accuracy, Precision, Recall, F1, ROC-AUC, PR-AUC, TN, FP, FN, TP, FPR, FPR@Recall=0.70)
- Leakage-free threshold tuning on Out-of-Fold (OOF) training data (F1-optimal & Profit-optimal)
- 4-Strategy marketing economics simulation (Everyone, Default, F1-optimal, Profit-optimal)
- Cumulative Gains and Decile Lift analysis
- Probability calibration using FrozenEstimator (scikit-learn 1.9+ compliant) with Brier scoring
- Bootstrap 95% Confidence Intervals for test metrics
- Explainability: Tree MDI, Permutation Importance, Logistic Odds Ratios, SHAP
- Customer persona profiling for both ACTUAL and PREDICTED responders
"""

import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict, Any, List, Tuple
from sklearn.base import clone
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    roc_curve, precision_recall_curve, brier_score_loss
)
from sklearn.inspection import permutation_importance
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.frozen import FrozenEstimator
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_predict

# Publication-grade plotting styles
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['font.sans-serif'] = 'Helvetica, Arial, DejaVu Sans'
plt.rcParams['font.size'] = 10
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['figure.titlesize'] = 14

# Marketing Economic Parameters
COST_PER_CONTACT = 5.0      # USD spent per marketing contact attempt
PROFIT_PER_RESPONDER = 50.0 # USD gross profit generated by a responding customer


def compute_metrics_at_threshold(y_true, y_proba, threshold: float = 0.50) -> Dict[str, Any]:
    """
    Computes classification metrics at a given decision threshold.
    """
    y_pred = (y_proba >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = float(fp / (fp + tn)) if (fp + tn) > 0 else 0.0
    
    acc = float(accuracy_score(y_true, y_pred))
    prec = float(precision_score(y_true, y_pred, zero_division=0))
    rec = float(recall_score(y_true, y_pred, zero_division=0))
    f1 = float(f1_score(y_true, y_pred, zero_division=0))
    try:
        roc_auc = float(roc_auc_score(y_true, y_proba))
    except Exception:
        roc_auc = 0.5
    try:
        pr_auc = float(average_precision_score(y_true, y_proba))
    except Exception:
        pr_auc = float(np.mean(y_true))
        
    return {
        'threshold': float(threshold),
        'accuracy': acc,
        'precision': prec,
        'recall': rec,
        'f1': f1,
        'roc_auc': roc_auc,
        'pr_auc': pr_auc,
        'tn': int(tn),
        'fp': int(fp),
        'fn': int(fn),
        'tp': int(tp),
        'fpr': fpr
    }


def compute_fpr_at_recall(y_true, y_proba, target_recall: float = 0.70) -> float:
    """
    Computes False Positive Rate at a fixed target recall (e.g. 70%)
    by inspecting the empirical ROC curve.
    """
    fpr_arr, tpr_arr, _ = roc_curve(y_true, y_proba)
    # Find smallest index where TPR >= target_recall
    valid_indices = np.where(tpr_arr >= target_recall)[0]
    if len(valid_indices) == 0:
        return 1.0
    return float(fpr_arr[valid_indices[0]])


def compute_top_k_capture(y_true, y_proba, k_percent: float = 20.0) -> Dict[str, Any]:
    """
    Computes the true top-k% responder capture rate:
      1. Rank all customers descending by predicted probability.
      2. Select the top k% of customers (by ranking, not fixed threshold).
      3. Count actual responders inside that top k% subset.
      4. Divide by total actual responders in the dataset.
    
    Formula:
      Top-k Capture Rate = (actual responders in top k%) / (total actual responders)
    """
    y_true_arr = np.asarray(y_true)
    y_proba_arr = np.asarray(y_proba)
    n_total = len(y_true_arr)
    total_responders = int(np.sum(y_true_arr))
    
    if total_responders == 0 or n_total == 0:
        return {
            'k_percent': float(k_percent),
            'n_targeted': 0,
            'responders_captured': 0,
            'total_responders': total_responders,
            'capture_rate': 0.0
        }
    
    n_top = int(np.floor(n_total * (k_percent / 100.0)))
    n_top = max(1, min(n_top, n_total))
    
    # Sort indices descending by predicted probability
    sort_idx = np.argsort(y_proba_arr)[::-1]
    top_idx = sort_idx[:n_top]
    
    responders_captured = int(np.sum(y_true_arr[top_idx]))
    capture_rate = float(responders_captured / total_responders)
    
    return {
        'k_percent': float(k_percent),
        'n_targeted': int(n_top),
        'responders_captured': int(responders_captured),
        'total_responders': int(total_responders),
        'capture_rate': float(capture_rate)
    }


def compute_bootstrap_ci(y_true, y_proba, threshold: float, n_bootstraps: int = 1000, random_state: int = 42) -> Dict[str, Dict[str, float]]:
    """
    Computes 95% bootstrap confidence intervals for ROC-AUC, PR-AUC, and F1 on the test set.
    Uses dedicated Generator instance to avoid mutating global random state.
    """
    rng = np.random.default_rng(random_state)
    n_samples = len(y_true)
    y_true_arr = np.asarray(y_true)
    y_proba_arr = np.asarray(y_proba)
    
    roc_aucs = []
    pr_aucs = []
    f1s = []
    
    for _ in range(n_bootstraps):
        idx = rng.choice(n_samples, size=n_samples, replace=True)
        sample_true = y_true_arr[idx]
        sample_proba = y_proba_arr[idx]
        
        # Guard against sample having only one class
        if len(np.unique(sample_true)) < 2:
            continue
            
        sample_pred = (sample_proba >= threshold).astype(int)
        roc_aucs.append(roc_auc_score(sample_true, sample_proba))
        pr_aucs.append(average_precision_score(sample_true, sample_proba))
        f1s.append(f1_score(sample_true, sample_pred, zero_division=0))
        
    return {
        'roc_auc': {
            'ci_lower': float(np.percentile(roc_aucs, 2.5)),
            'ci_upper': float(np.percentile(roc_aucs, 97.5)),
            'std': float(np.std(roc_aucs))
        },
        'pr_auc': {
            'ci_lower': float(np.percentile(pr_aucs, 2.5)),
            'ci_upper': float(np.percentile(pr_aucs, 97.5)),
            'std': float(np.std(pr_aucs))
        },
        'f1': {
            'ci_lower': float(np.percentile(f1s, 2.5)),
            'ci_upper': float(np.percentile(f1s, 97.5)),
            'std': float(np.std(f1s))
        }
    }


def find_optimal_thresholds_oof(
    y_train_true,
    y_train_oof_proba,
    cost_per_contact: float = COST_PER_CONTACT,
    profit_per_responder: float = PROFIT_PER_RESPONDER,
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """
    Optimizes classification thresholds strictly on training Out-Of-Fold (OOF) predictions:
      (a) F1-Optimal threshold: maximizes F1 on training OOF predictions.
      (b) Profit-Optimal threshold: maximizes net profit on training OOF predictions.
    Generates threshold trade-off curve and saves to reports/figures/.
    """
    os.makedirs(output_dir, exist_ok=True)
    thresholds = np.linspace(0.05, 0.95, 91)
    
    f1s = []
    precisions = []
    recalls = []
    fprs = []
    net_profits = []
    
    y_true_arr = np.asarray(y_train_true)
    
    for t in thresholds:
        pred = (y_train_oof_proba >= t).astype(int)
        tp = int(np.sum((pred == 1) & (y_true_arr == 1)))
        fp = int(np.sum((pred == 1) & (y_true_arr == 0)))
        tn = int(np.sum((pred == 0) & (y_true_arr == 0)))
        fn = int(np.sum((pred == 0) & (y_true_arr == 1)))
        
        f1s.append(f1_score(y_true_arr, pred, zero_division=0))
        precisions.append(precision_score(y_true_arr, pred, zero_division=0))
        recalls.append(recall_score(y_true_arr, pred, zero_division=0))
        fprs.append(fp / (fp + tn) if (fp + tn) > 0 else 0.0)
        
        # Net Profit = TP * profit_per_responder - (TP + FP) * cost_per_contact
        profit = tp * profit_per_responder - (tp + fp) * cost_per_contact
        net_profits.append(profit)
        
    f1s = np.array(f1s)
    net_profits = np.array(net_profits)
    
    # Identify optimal threshold indices
    best_f1_idx = int(np.argmax(f1s))
    best_profit_idx = int(np.argmax(net_profits))
    
    opt_f1_threshold = float(thresholds[best_f1_idx])
    opt_profit_threshold = float(thresholds[best_profit_idx])
    
    # Plotting trade-off dynamics
    fig, ax1 = plt.subplots(figsize=(10, 6))
    
    ax1.plot(thresholds, precisions, label='Precision', color='#2ca02c', lw=2)
    ax1.plot(thresholds, recalls, label='Recall', color='#1f77b4', lw=2)
    ax1.plot(thresholds, f1s, label='F1-Score', color='#d62728', lw=2.5)
    ax1.plot(thresholds, fprs, label='False Positive Rate (FPR)', color='#ff7f0e', lw=1.8, linestyle='--')
    ax1.set_xlabel('Classification Decision Threshold')
    ax1.set_ylabel('Metric Score (0.0 to 1.0)')
    ax1.set_xlim([0.05, 0.95])
    ax1.set_ylim([0.0, 1.05])
    
    # Second y-axis for profit curve
    ax2 = ax1.twinx()
    ax2.plot(thresholds, net_profits, label='Net Campaign Profit ($)', color='#9467bd', lw=2, linestyle='-.')
    ax2.set_ylabel('Net Marketing Profit ($ USD)', color='#9467bd')
    ax2.tick_params(axis='y', labelcolor='#9467bd')
    
    # Mark thresholds
    ax1.axvline(0.50, color='gray', linestyle=':', label='Default (0.50)')
    ax1.axvline(opt_f1_threshold, color='#d62728', linestyle='--', label=f'F1-Optimal ({opt_f1_threshold:.2f})')
    ax1.axvline(opt_profit_threshold, color='#2ca02c', linestyle='-', lw=2, label=f'Profit-Optimal ({opt_profit_threshold:.2f})')
    
    plt.title('Out-Of-Fold (OOF) Decision Threshold Optimization & Financial Trade-Offs', fontweight='bold', pad=15)
    
    # Combine legends
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='center right', frameon=True)
    plt.tight_layout()
    
    plot_path = os.path.join(output_dir, "threshold_tuning.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()
    
    return {
        'f1_optimal_threshold': opt_f1_threshold,
        'f1_optimal_oof_score': float(f1s[best_f1_idx]),
        'profit_optimal_threshold': opt_profit_threshold,
        'profit_optimal_oof_profit': float(net_profits[best_profit_idx]),
        'plot_path': plot_path
    }


def run_four_strategy_simulation(
    y_test_true,
    y_test_proba,
    f1_threshold: float,
    profit_threshold: float,
    cost_per_contact: float = COST_PER_CONTACT,
    profit_per_responder: float = PROFIT_PER_RESPONDER,
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """
    Evaluates four strategic outreach policies on the held-out test set:
      - Strategy 1: Contact Everyone (Mass Spray & Pray, t = 0.00)
      - Strategy 2: Default ML (t = 0.50)
      - Strategy 3: F1-Optimal ML (t = f1_threshold)
      - Strategy 4: Profit-Optimal ML (t = profit_threshold)
    """
    os.makedirs(output_dir, exist_ok=True)
    n_customers = len(y_test_true)
    actual_responders_total = int(np.sum(y_test_true))
    
    strategies = [
        ('Strategy 1: Contact Everyone', 0.00),
        ('Strategy 2: Default ML (Threshold 0.50)', 0.50),
        (f'Strategy 3: F1-Optimal (Threshold {f1_threshold:.2f})', f1_threshold),
        (f'Strategy 4: Profit-Optimal (Threshold {profit_threshold:.2f})', profit_threshold)
    ]
    
    rows = []
    cost_everyone = n_customers * cost_per_contact
    
    for name, t in strategies:
        m = compute_metrics_at_threshold(y_test_true, y_test_proba, threshold=t)
        contacts = m['tp'] + m['fp']
        responders = m['tp']
        wasted_contacts = m['fp']
        cost = contacts * cost_per_contact
        gross_rev = responders * profit_per_responder
        net_profit = gross_rev - cost
        roi = (net_profit / cost * 100.0) if cost > 0 else 0.0
        cost_saved_pct = ((cost_everyone - cost) / cost_everyone) * 100.0 if cost_everyone > 0 else 0.0
        
        rows.append({
            'Strategy': name,
            'Threshold': float(t),
            'Targeted Contacts': int(contacts),
            'Total Cost ($)': float(cost),
            'Responders Reached': int(responders),
            'Wasted Contacts (FP)': int(wasted_contacts),
            'Gross Revenue ($)': float(gross_rev),
            'Net Profit ($)': float(net_profit),
            'ROI (%)': float(roi),
            'Cost Saved vs All (%)': float(cost_saved_pct)
        })
        
    sim_df = pd.DataFrame(rows)
    
    # Financial Visualization
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    short_names = ['1: Everyone', '2: Default 0.50', f'3: F1 ({f1_threshold:.2f})', f'4: Profit ({profit_threshold:.2f})']
    colors = ['#7f7f7f', '#1f77b4', '#d62728', '#2ca02c']
    
    # 1. Total Cost
    bars1 = axes[0].bar(short_names, sim_df['Total Cost ($)'], color=colors, edgecolor='black', alpha=0.85)
    axes[0].set_title("Total Campaign Spend ($)", fontweight='bold')
    axes[0].set_ylabel("USD ($)")
    for b in bars1:
        axes[0].text(b.get_x() + b.get_width()/2, b.get_height() + 50, f"${b.get_height():,.0f}",
                     ha='center', va='bottom', fontweight='bold', fontsize=9)
                     
    # 2. Net Profit
    bars2 = axes[1].bar(short_names, sim_df['Net Profit ($)'], color=colors, edgecolor='black', alpha=0.85)
    axes[1].set_title("Net Campaign Profit ($)", fontweight='bold')
    axes[1].set_ylabel("USD ($)")
    for b in bars2:
        axes[1].text(b.get_x() + b.get_width()/2, b.get_height() + 50, f"${b.get_height():,.0f}",
                     ha='center', va='bottom', fontweight='bold', fontsize=9)
                     
    # 3. ROI
    bars3 = axes[2].bar(short_names, sim_df['ROI (%)'], color=colors, edgecolor='black', alpha=0.85)
    axes[2].set_title("Return on Marketing Spend (ROI %)", fontweight='bold')
    axes[2].set_ylabel("Percentage (%)")
    for b in bars3:
        axes[2].text(b.get_x() + b.get_width()/2, b.get_height() + 10, f"{b.get_height():.1f}%",
                     ha='center', va='bottom', fontweight='bold', fontsize=9)
                     
    plt.suptitle(f"Marketing Financial Simulation Across 4 Strategies (Cost/Contact = ${cost_per_contact}, Profit/Responder = ${profit_per_responder})",
                 fontweight='bold', fontsize=14, y=1.02)
    plt.tight_layout()
    
    plot_path = os.path.join(output_dir, "business_simulation_roi.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()
    
    return {
        'simulation_table': sim_df,
        'plot_path': plot_path
    }


def evaluate_probability_calibration(
    base_model_pipeline,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    random_state: int = 42,
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """
    Calibrates model probability using FrozenEstimator (scikit-learn 1.9+ compliant).
    Trains cloned base model on 75% sub-train, calibrates via 5-fold CV over validation data
    for fair out-of-fold Brier comparison, and evaluates on test set.
    Never mutates base_model_pipeline.
    """
    os.makedirs(output_dir, exist_ok=True)
    X_subtrain, X_val, y_subtrain, y_val = train_test_split(
        X_train, y_train, test_size=0.25, random_state=random_state, stratify=y_train
    )
    
    # Fit base pipeline clone on sub-train to prevent mutating input model
    base_clone = clone(base_model_pipeline)
    base_clone.fit(X_subtrain, y_subtrain)
    val_uncal_p = base_clone.predict_proba(X_val)[:, 1]
    
    # Compute uncalibrated validation Brier (out-of-sample on X_val)
    brier_val_uncal = float(brier_score_loss(y_val, val_uncal_p))
    
    # Fair Out-Of-Fold calibrated probabilities on X_val to avoid in-sample calibration leakage
    frozen_subtrain = FrozenEstimator(base_clone)
    cv_val = StratifiedKFold(n_splits=5, shuffle=True, random_state=random_state)
    val_cal_p = cross_val_predict(
        CalibratedClassifierCV(estimator=frozen_subtrain, method='sigmoid'),
        X_val, y_val, cv=cv_val, method='predict_proba'
    )[:, 1]
    
    # Compute calibrated validation Brier (apples-to-apples out-of-fold)
    brier_val_cal = float(brier_score_loss(y_val, val_cal_p))
    val_improved = bool(brier_val_cal < brier_val_uncal)
    
    # Fit calibrator on all validation data using frozen subtrain model for test evaluation and plot
    calibrator_val = CalibratedClassifierCV(estimator=frozen_subtrain, method='sigmoid')
    calibrator_val.fit(X_val, y_val)
    
    test_uncal_p = base_clone.predict_proba(X_test)[:, 1]
    test_cal_p = calibrator_val.predict_proba(X_test)[:, 1]
    
    brier_test_uncal = float(brier_score_loss(y_test, test_uncal_p))
    brier_test_cal = float(brier_score_loss(y_test, test_cal_p))
    
    # Reliability diagram
    prob_true_uncal, prob_pred_uncal = calibration_curve(y_test, test_uncal_p, n_bins=10)
    prob_true_cal, prob_pred_cal = calibration_curve(y_test, test_cal_p, n_bins=10)
    
    plt.figure(figsize=(8, 6))
    plt.plot([0, 1], [0, 1], "k:", label="Perfect Calibration")
    plt.plot(prob_pred_uncal, prob_true_uncal, "s-", color='#1f77b4', lw=2,
             label=f"Uncalibrated Model (Test Brier: {brier_test_uncal:.4f})")
    plt.plot(prob_pred_cal, prob_true_cal, "o-", color='#2ca02c', lw=2,
             label=f"Calibrated Model (Test Brier: {brier_test_cal:.4f})")
             
    plt.title("Reliability Diagram: Probability Calibration Analysis", fontweight='bold', pad=15)
    plt.xlabel("Mean Predicted Probability")
    plt.ylabel("Observed Fraction of Responders")
    plt.ylim([-0.05, 1.05])
    plt.xlim([-0.05, 1.05])
    plt.legend(loc="lower right", frameon=True)
    plt.tight_layout()
    
    plot_path = os.path.join(output_dir, "calibration_curve.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()
    
    return {
        'brier_val_uncalibrated': brier_val_uncal,
        'brier_val_calibrated': brier_val_cal,
        'brier_test_uncalibrated': brier_test_uncal,
        'brier_test_calibrated': brier_test_cal,
        'val_improved': val_improved,
        'plot_path': plot_path
    }


def compute_comprehensive_customer_profiles(X_test: pd.DataFrame, y_true: pd.Series, y_pred: np.ndarray) -> pd.DataFrame:
    """
    Computes summary attributes for:
      (a) ACTUAL Responders vs ACTUAL Non-Responders
      (b) PREDICTED Responders vs PREDICTED Non-Responders
    """
    df_eval = X_test.copy()
    df_eval['actual_status'] = np.where(y_true == 1, 'Actual Responder', 'Actual Non-Responder')
    df_eval['predicted_status'] = np.where(y_pred == 1, 'Predicted Responder', 'Predicted Non-Responder')
    
    numeric_cols = [c for c in df_eval.columns if c in [
        'age', 'campaign', 'pdays', 'previous',
        'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
        'euribor3m', 'nr.employed'
    ]]
    if not numeric_cols:
        numeric_cols = df_eval.select_dtypes(include=[np.number]).columns.tolist()
    
    actual_summary = df_eval.groupby('actual_status')[numeric_cols].agg(['mean', 'median']).round(2)
    predicted_summary = df_eval.groupby('predicted_status')[numeric_cols].agg(['mean', 'median']).round(2)
    
    combined = pd.concat([actual_summary, predicted_summary])
    return combined


def plot_metrics_comparison(results_df: pd.DataFrame, output_dir: str = "reports/figures") -> str:
    """Produces comparative bar chart across all algorithms."""
    os.makedirs(output_dir, exist_ok=True)
    metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC', 'PR-AUC']
    
    plot_df = results_df.copy()
    df_melted = plot_df.melt(
        id_vars=['Model'],
        value_vars=[c for c in metrics_to_plot if c in plot_df.columns],
        var_name='Metric',
        value_name='Score'
    )
    
    plt.figure(figsize=(13, 6))
    palette = sns.color_palette("tab10", len(results_df['Model'].unique()))
    sns.barplot(
        data=df_melted,
        x='Metric',
        y='Score',
        hue='Model',
        palette=palette,
        edgecolor='black',
        alpha=0.9
    )
    plt.title("Comparative Performance Across 6 Machine Learning Models (Held-Out Test Set)", fontweight='bold', pad=15)
    plt.ylim(0.0, 1.05)
    plt.ylabel("Score")
    plt.xlabel("")
    plt.legend(title="Algorithm", bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "metrics_comparison_bar.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_roc_curves(models_dict: Dict[str, Any], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """Plots Receiver Operating Characteristic (ROC) curves."""
    os.makedirs(output_dir, exist_ok=True)
    plt.figure(figsize=(9, 7))
    palette = sns.color_palette("tab10", len(models_dict))
    
    for i, (name, model) in enumerate(models_dict.items()):
        y_proba = model.predict_proba(X_test)[:, 1]
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        auc_score = roc_auc_score(y_test, y_proba)
        plt.plot(fpr, tpr, label=f"{name} (AUC = {auc_score:.3f})", color=palette[i], lw=2)
        
    plt.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Guessing (AUC = 0.500)')
    plt.xlim([-0.02, 1.02])
    plt.ylim([-0.02, 1.02])
    plt.xlabel("False Positive Rate (1 - Specificity)")
    plt.ylabel("True Positive Rate (Sensitivity / Recall)")
    plt.title("Receiver Operating Characteristic (ROC) Curves - All Models", fontweight='bold', pad=15)
    plt.legend(loc='lower right', frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "roc_curves_all_models.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_precision_recall_curves(models_dict: Dict[str, Any], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """Plots Precision-Recall (PR) curves."""
    os.makedirs(output_dir, exist_ok=True)
    plt.figure(figsize=(9, 7))
    baseline = np.mean(y_test)
    palette = sns.color_palette("tab10", len(models_dict))
    
    for i, (name, model) in enumerate(models_dict.items()):
        y_proba = model.predict_proba(X_test)[:, 1]
        prec, rec, _ = precision_recall_curve(y_test, y_proba)
        pr_auc = average_precision_score(y_test, y_proba)
        plt.plot(rec, prec, label=f"{name} (PR-AUC = {pr_auc:.3f})", color=palette[i], lw=2)
        
    plt.axhline(baseline, color='k', linestyle='--', lw=1.5, label=f"Baseline Prevalence ({baseline:.1%})")
    plt.xlim([-0.02, 1.02])
    plt.ylim([-0.02, 1.02])
    plt.xlabel("Recall (Sensitivity)")
    plt.ylabel("Precision (Positive Predictive Value)")
    plt.title("Precision-Recall (PR) Curves - All Models", fontweight='bold', pad=15)
    plt.legend(loc='upper right', frameon=True)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "pr_curves_all_models.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_confusion_matrices(models_dict: Dict[str, Any], thresholds_dict: Dict[str, float], X_test, y_test, output_dir: str = "reports/figures") -> str:
    """Plots 2x3 confusion matrix grid evaluated at each model's own optimal threshold."""
    os.makedirs(output_dir, exist_ok=True)
    fig, axes = plt.subplots(2, 3, figsize=(15, 9))
    axes = axes.flatten()
    
    for i, (name, model) in enumerate(models_dict.items()):
        y_proba = model.predict_proba(X_test)[:, 1]
        t = thresholds_dict.get(name, 0.50)
        y_pred = (y_proba >= t).astype(int)
        cm = confusion_matrix(y_test, y_pred)
        
        cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        annot = np.array([
            [f"{cm[0, 0]}\n({cm_norm[0, 0]:.1%})", f"{cm[0, 1]}\n({cm_norm[0, 1]:.1%})"],
            [f"{cm[1, 0]}\n({cm_norm[1, 0]:.1%})", f"{cm[1, 1]}\n({cm_norm[1, 1]:.1%})"]
        ])
        
        sns.heatmap(
            cm,
            annot=annot,
            fmt='',
            cmap='Blues',
            cbar=False,
            ax=axes[i],
            xticklabels=['Non-Responder', 'Responder'],
            yticklabels=['Non-Responder', 'Responder'],
            linewidths=1,
            linecolor='grey'
        )
        axes[i].set_title(f"{name} (t = {t:.2f})", fontweight='bold', pad=8)
        axes[i].set_xlabel("Predicted")
        axes[i].set_ylabel("Actual")
        
    plt.suptitle("Confusion Matrix Heatmaps Evaluated at Each Model's Out-Of-Fold Optimal Threshold", fontweight='bold', fontsize=14, y=0.98)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "confusion_matrices_grid.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def plot_cumulative_gains_and_lift(best_model, X_test, y_test, output_dir: str = "reports/figures") -> str:
    """Computes and plots Cumulative Gains and Decile Lift charts."""
    os.makedirs(output_dir, exist_ok=True)
    y_proba = best_model.predict_proba(X_test)[:, 1]
    
    df_eval = pd.DataFrame({'actual': np.asarray(y_test), 'prob': y_proba})
    df_eval = df_eval.sort_values(by='prob', ascending=False).reset_index(drop=True)
    df_eval['decile'] = pd.qcut(df_eval.index, q=10, labels=range(1, 11))
    
    total_responders = df_eval['actual'].sum()
    total_customers = len(df_eval)
    
    df_eval['cum_responders'] = df_eval['actual'].cumsum()
    df_eval['cum_pct_responders'] = (df_eval['cum_responders'] / total_responders) * 100
    df_eval['cum_pct_customers'] = ((df_eval.index + 1) / total_customers) * 100
    
    decile_summary = df_eval.groupby('decile', observed=False).agg(
        total_in_decile=('actual', 'count'),
        responders_in_decile=('actual', 'sum')
    ).reset_index()
    decile_summary['response_rate'] = (decile_summary['responders_in_decile'] / decile_summary['total_in_decile']) * 100
    baseline_rate = (total_responders / total_customers) * 100
    decile_summary['lift'] = decile_summary['response_rate'] / baseline_rate
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    
    # Gains
    axes[0].plot(df_eval['cum_pct_customers'], df_eval['cum_pct_responders'], label='ML Model Gains', color='#1f77b4', lw=2.5)
    axes[0].plot([0, 100], [0, 100], 'k--', label='Random Targeting', lw=1.5)
    for pct in [20, 30]:
        idx = int(total_customers * (pct / 100)) - 1
        gain = df_eval.loc[idx, 'cum_pct_responders']
        axes[0].scatter([pct], [gain], color='#d62728', s=60, zorder=5)
        axes[0].annotate(f"Top {pct}%: {gain:.1f}% responders",
                         xy=(pct, gain), xytext=(pct + 5, gain - 8),
                         arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
                         fontweight='bold')
    axes[0].set_title("Cumulative Gains Chart", fontweight='bold')
    axes[0].set_xlabel("Percentage of Customers Contacted (%)")
    axes[0].set_ylabel("Cumulative % Responders Captured")
    axes[0].set_xlim([0, 100])
    axes[0].set_ylim([0, 105])
    axes[0].legend(loc='lower right', frameon=True)
    
    # Lift
    sns.barplot(data=decile_summary, x='decile', y='lift', color='#2ca02c', ax=axes[1], edgecolor='black', alpha=0.85)
    axes[1].axhline(1.0, color='red', linestyle='--', lw=1.5, label='Baseline Lift (1.0x)')
    axes[1].set_title("Decile Lift Curve", fontweight='bold')
    axes[1].set_xlabel("Customer Decile (Ranked by Propensity)")
    axes[1].set_ylabel("Lift Multiplier vs Random")
    for p in axes[1].patches:
        height = p.get_height()
        if height > 0:
            axes[1].annotate(f"{height:.2f}x",
                             (p.get_x() + p.get_width() / 2., height),
                             ha='center', va='bottom', xytext=(0, 3),
                             textcoords='offset points', fontweight='bold', fontsize=9)
    axes[1].legend(loc='upper right', frameon=True)
    
    plt.suptitle("Targeting Efficiency: Gains and Decile Lift Analysis", fontweight='bold', fontsize=14, y=1.01)
    plt.tight_layout()
    
    filepath = os.path.join(output_dir, "cumulative_gains_lift.png")
    plt.savefig(filepath, dpi=300)
    plt.close()
    return filepath


def analyze_feature_importances(
    best_tree_model, lr_model,
    X_test, y_test,
    feature_names: List[str],
    output_dir: str = "reports/figures"
) -> Dict[str, Any]:
    """Generates Tree MDI, Permutation Importance, Odds Ratios, and SHAP plots."""
    os.makedirs(output_dir, exist_ok=True)
    plots = {}
    
    # 1. Tree-based MDI
    tree_estimator = best_tree_model.named_steps.get('classifier', best_tree_model)
    if hasattr(tree_estimator, 'feature_importances_'):
        importances = tree_estimator.feature_importances_
        fi_df = pd.DataFrame({'feature': feature_names, 'importance': importances})
        fi_df = fi_df.sort_values('importance', ascending=True)
        if len(fi_df) > 20:
            fi_df = fi_df.tail(20)
        
        plt.figure(figsize=(10, 7))
        plt.barh(fi_df['feature'], fi_df['importance'], color='#1f77b4', edgecolor='black', alpha=0.85)
        plt.title("Tree-Based Feature Importances (Top 20 MDI)", fontweight='bold', pad=12)
        plt.xlabel("Relative Importance")
        plt.tight_layout()
        fi_path = os.path.join(output_dir, "feature_importance_tree.png")
        plt.savefig(fi_path, dpi=300)
        plt.close()
        plots['tree_importance'] = fi_path
        
    # 2. Permutation Importance
    perm_res = permutation_importance(best_tree_model, X_test, y_test, n_repeats=5, random_state=42, scoring='f1')
    perm_df = pd.DataFrame({
        'feature': X_test.columns,
        'mean_importance': perm_res.importances_mean,
        'std': perm_res.importances_std
    }).sort_values('mean_importance', ascending=True)
    if len(perm_df) > 20:
        perm_df = perm_df.tail(20)
    
    plt.figure(figsize=(10, 7))
    plt.barh(perm_df['feature'], perm_df['mean_importance'], xerr=perm_df['std'], color='#2ca02c', edgecolor='black', alpha=0.85)
    plt.title("Permutation Feature Importance on Test Set (Top F1 Degradation)", fontweight='bold', pad=12)
    plt.xlabel("Mean F1-Score Decrease Upon Feature Permutation")
    plt.tight_layout()
    perm_path = os.path.join(output_dir, "feature_importance_permutation.png")
    plt.savefig(perm_path, dpi=300)
    plt.close()
    plots['permutation_importance'] = perm_path
    
    # 3. Logistic Regression Odds Ratios
    lr_estimator = lr_model.named_steps.get('classifier', lr_model)
    if hasattr(lr_estimator, 'coef_'):
        coefs = lr_estimator.coef_[0]
        odds_ratios = np.exp(coefs)
        or_df = pd.DataFrame({
            'feature': feature_names,
            'odds_ratio': odds_ratios,
            'abs_log_or': np.abs(coefs)
        }).sort_values('abs_log_or', ascending=True)
        if len(or_df) > 20:
            or_df = or_df.tail(20)
        or_df = or_df.sort_values('odds_ratio', ascending=True)
        
        plt.figure(figsize=(10, 7))
        colors = ['#d62728' if x < 1.0 else '#1f77b4' for x in or_df['odds_ratio']]
        plt.barh(or_df['feature'], or_df['odds_ratio'], color=colors, edgecolor='black', alpha=0.85)
        plt.axvline(1.0, color='k', linestyle='--', lw=1.2, label='Baseline (Odds Ratio = 1.0)')
        plt.title("Logistic Regression Predictors: Odds Ratios (Top 20 Drivers)", fontweight='bold', pad=12)
        plt.xlabel("Odds Ratio (> 1.0 indicates elevated subscription odds)")
        plt.legend(loc='lower right')
        plt.tight_layout()
        or_path = os.path.join(output_dir, "feature_importance_odds_ratios.png")
        plt.savefig(or_path, dpi=300)
        plt.close()
        plots['odds_ratios'] = or_path
        
    # 4. SHAP Summary Plot
    try:
        import shap
        preprocessor = best_tree_model.named_steps['preprocessor']
        sample_size = min(300, len(X_test))
        X_test_sub = X_test.sample(sample_size, random_state=42)
        X_test_trans = preprocessor.transform(X_test_sub)
        explainer = shap.TreeExplainer(tree_estimator)
        shap_values = explainer.shap_values(X_test_trans)
        
        if isinstance(shap_values, list):
            sv = shap_values[1]
        elif hasattr(shap_values, 'shape') and len(shap_values.shape) == 3:
            sv = shap_values[:, :, 1]
        else:
            sv = shap_values
            
        plt.figure(figsize=(10, 7))
        shap.summary_plot(sv, X_test_trans, feature_names=feature_names, max_display=15, show=False)
        plt.title("SHAP Feature Attribution & Impact Distribution (Top 15 Drivers)", fontweight='bold', pad=15)
        plt.tight_layout()
        shap_path = os.path.join(output_dir, "shap_summary.png")
        plt.savefig(shap_path, dpi=300, bbox_inches='tight')
        plt.close()
        plots['shap'] = shap_path
    except Exception as e:
        print(f"SHAP explanation note: {e}")
        plots['shap'] = None
        
    return plots
